title: Gustav Arend – Portfolio
description: Automatisering & Scripting · Cloud Computing & DevOps
author: Gustav Arend
email: you@example.com
theme: minima
# Enable friendly URLs
permalink: /:categories/:year/:month/:day/:title/
# Plugins (supported by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/YOUR_GITHUB_USERNAME" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/YOUR_LINKEDIN/" }

# Collections (optional)
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults for markdown pages
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: post
      author: Gustav Arend
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Gustav Arend
